
import numpy
import numpy as np
import natsort

import Library.FormatUtils
from Library import Stats
from Library import Settings
from Library import Legend
from Library import AnalysisStep


from matplotlib import pyplot as plt
from scipy.stats import ks_2samp
import matplotlib

import pickle

##########################
alpha_level = 0.001
output_folder = 'steps_output/'
dependent_variable = 'steps'
figure_size = (12, 8)

# Per-cat day caps. Generated by SCRIPT_process_drinking.py (printed as max_days_log).
# Applied below as `selected_cat.query('days <= @max_allowed_day')`, so they filter data
# *before* the baseline regression and KS tests — they affect the statistics, not just the plot.
# Purpose: truncate the steps analysis to the same window as phase-1 drinking. Citrine and Elia
# have additional date cutoffs in phase 1 (see AnalysisDrink.read_data), which is why their
# caps (77 and 91) differ from Bernie and Minerva (both 83).
max_days_per_cat = {'Bernie': 83, 'Citrine': 77, 'Elia': 91, 'Minerva': 83}
max_day_range = 91
##########################

matplotlib.rcParams['font.family'] = 'serif'
colors = Settings.colors
data = AnalysisStep.read_data()

cats = list(data.subject.unique())
cats = natsort.natsorted(cats)
intervals = data.interval.unique()
intervals = intervals[~np.isnan(intervals)]


plt.figure(figsize=figure_size)
tests_output = open(f'{output_folder}statistics_steps.txt', 'w')

regression_results = {}

for plot_index, cat_name in enumerate(cats):
    if plot_index == 0: plot_nr = 1
    if plot_index == 1: plot_nr = 2
    if plot_index == 2: plot_nr = 4
    if plot_index == 3: plot_nr = 5

    plt.subplot(2, 3, plot_nr)
    selected_cat = data.query('subject ==@cat_name')
    selected_cat.loc[:, 'days'] = selected_cat['days'] - numpy.min(selected_cat['days'])
    max_allowed_day = max_days_per_cat[cat_name]
    selected_cat = selected_cat.query('days <= @max_allowed_day')

    grp = selected_cat.groupby(['days', 'interval', 'Intervention'], observed=False)
    grp = grp['steps'].sum()
    selected_cat = grp.reset_index()
    selected_cat['steps'] = selected_cat['steps'] / 1000
    selected_cat = selected_cat.query('steps > 0') # Remove the days where the cat did not wear the Fitbit

    # Run regression on baseline data
    base_line_data = selected_cat.query('Intervention == False')
    regression_result = Stats.regression(base_line_data, dependent_variable, alpha_level)
    regression_results[cat_name] = regression_result
    residuals = regression_result['residuals']

    custom_legend = Legend.CustomLegend()
    for interval in intervals:
        selected_interval_data = selected_cat.query('interval == @interval')

        transparency = 1
        size = 50

        if interval > 0: transparency = 0.25
        if interval == 0: size = 25
        interval_str = str(int(interval))
        if interval_str == '0': interval_str = 'baseline'
        plt.scatter(selected_interval_data.days, selected_interval_data[dependent_variable], color=colors[interval_str], alpha=transparency, s=size)
        custom_legend.add_entry(label='Baseline', color='gray', marker='o', linestyle='')

        if interval > 0:
            current_color = colors[interval_str]
            mn_day = numpy.mean(selected_interval_data.days)

            prediction = Stats.predict(regression_result, selected_interval_data.days)
            prediction_errors = selected_interval_data[dependent_variable] - prediction
            prediction_errors = prediction_errors[~np.isnan(prediction_errors)]

            stat, ks_result_p = ks_2samp(residuals, prediction_errors)
            formatted = Library.FormatUtils.format_ktest_result_apa(stat, ks_result_p, alpha_level)

            marker = '+'
            size = 150
            if ks_result_p < alpha_level: marker = '*'
            mn_session = numpy.nanmean(selected_interval_data[dependent_variable])
            plt.scatter(mn_day, mn_session, marker=marker, s=150, color=current_color)
            interval = str(int(interval))
            custom_legend.add_entry(label=interval_str + 's', color=current_color, marker='o', linestyle='')
            #print(interval, predicted, mn_session, max_day)
            statistics_line = f'{cat_name}, interval {interval}s vs Baseline, {formatted}\n'
            tests_output.write(statistics_line)

    custom_legend.add_entry(label=f'Interval Mean, $p$ > {alpha_level}', color='black', marker='+', linestyle='')
    custom_legend.add_entry(label=f'Interval Mean, $p$ < {alpha_level}', color='black', marker='*', linestyle='')
    custom_legend.add_entry(label='Baseline Regression', color='gray', marker='None', linestyle='--')

    Stats.plot_line(regression_result, colors['baseline'])
    if cat_name in ['Bernie', 'Citrine']: plt.ylim(0, 30)
    if cat_name in ['Elia', 'Minerva']: plt.ylim(0, 8)
    plt.xlim(-1, max_day_range)

    plt.title(cat_name, fontsize=18)

    ax = plt.gca()

    if plot_index in [0, 2]: plt.ylabel('Steps (1000)', fontsize=16)
    if plot_index not in [0,2]: ax.set_yticks([])
    if plot_index in [0, 1]: ax.set_xticks([])
    plt.xlabel('Days', fontsize=18)
    if plot_index in [0, 1]: plt.xlabel('')

    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_visible(False)
    ax.spines['bottom'].set_visible(False)

    plt.xticks(fontsize=16)  # X-axis tick labels font size
    plt.yticks(fontsize=16)  # Y-axis tick labels font size

    ax = plt.gca()
    ax.set_facecolor('#F1F0EA')


plt.subplot(2, 3, 3)
plt.axis('off')
custom_legend.draw_legend('upper left')
plt.tight_layout()

output_file = f"{output_folder}steps.png"
plt.savefig(output_file, dpi=300)

output_file = f"{output_folder}steps.pdf"
plt.savefig(output_file)

plt.show()
tests_output.close()

pickle_file = f"{output_folder}regression.pck"
pickle_file_handle = open(pickle_file, 'wb')
pickle.dump(regression_results, pickle_file_handle)
pickle_file_handle.close()

