
import numpy
import numpy as np
import natsort

from Library import Stats
from Library import Settings
from Library import Utils
from Library import Legend
from Library import StepAnalysis
from scipy.stats import ttest_ind
from matplotlib import pyplot as plt
from scipy.stats import kstest, norm
import matplotlib

##########################
alpha_level = 0.0005
output_folder = 'steps_output/'
dependent_variable = 'steps'
figure_size = (12, 8)

# This is generated by SCRIPT_process_drinking.py
max_days_per_cat = {'Bernie': 83, 'Citrine': 77, 'Elia': 91, 'Minerva': 83}
max_day_range = 91
##########################

matplotlib.rcParams['font.family'] = 'serif'
colors = Settings.colors
data = StepAnalysis.read_data()

cats = list(data.subject.unique())
cats = natsort.natsorted(cats)
intervals = data.interval.unique()
intervals = intervals[~np.isnan(intervals)]


plt.figure(figsize=figure_size)
tests_output = open(f'{output_folder}statistics_steps.txt', 'w')

for plot_index, cat_name in enumerate(cats):
    if plot_index == 0: plot_nr = 1
    if plot_index == 1: plot_nr = 2
    if plot_index == 2: plot_nr = 4
    if plot_index == 3: plot_nr = 5

    plt.subplot(2, 3, plot_nr)
    selected_cat = data.query('subject ==@cat_name')
    selected_cat.loc[:, 'days'] = selected_cat['days'] - numpy.min(selected_cat['days'])
    max_allowed_day = max_days_per_cat[cat_name]
    selected_cat = selected_cat.query('days <= @max_allowed_day')

    grp = selected_cat.groupby(['days', 'interval', 'Intervention'], observed=False)
    grp = grp['steps'].sum()
    selected_cat = grp.reset_index()
    selected_cat['steps'] = selected_cat['steps'] / 1000
    selected_cat = selected_cat.query('steps > 0') # Remove the days where the cat did not wear the Fitbit

    # Run regression on baseline data
    base_line_data = selected_cat.query('Intervention == False')
    regression_result = Stats.regression(base_line_data, dependent_variable, alpha_level)
    residuals = regression_result['residuals']

    custom_legend = Legend.CustomLegend()
    for interval in intervals:
        selected_interval_data = selected_cat.query('interval == @interval')

        transparency = 1
        size = 50

        if interval > 0: transparency = 0.25
        if interval == 0: size = 25
        interval_str = str(int(interval))
        if interval_str == '0': interval_str = 'baseline'
        plt.scatter(selected_interval_data.days, selected_interval_data[dependent_variable], color=colors[interval_str], alpha=transparency, s=size)
        custom_legend.add_entry(label='Baseline', color='gray', marker='o', linestyle='')

        if interval > 0:
            current_color = colors[interval_str]
            mn_day = numpy.mean(selected_interval_data.days)
            prediction_mean = Stats.predict(regression_result, mn_day)
            prediction_std = regression_result['prstd']
            shifted_residuals = residuals + prediction_mean
            shifted_residuals_std = np.std(shifted_residuals)
            session_data = selected_interval_data[dependent_variable].values
            print(shifted_residuals_std, prediction_std)

            try:
                session_data = session_data[~np.isnan(session_data)]
                stat, ks_result_p = kstest(session_data, 'norm', args=(prediction_mean, shifted_residuals_std))
            except ValueError as ve:
                stat = 'NaN'
                ks_result_p = 1

            formatted1 = Utils.format_ktest_result_apa(stat, ks_result_p, alpha_level)

            tt_result = ttest_ind(session_data, shifted_residuals)
            tt_result_p = tt_result[1]
            formatted2 = Utils.format_ttest_result_apa(tt_result, alpha_level)

            marker = '+'
            size = 150
            if ks_result_p < alpha_level: marker = '*'
            mn_session = numpy.nanmean(selected_interval_data[dependent_variable])
            plt.scatter(mn_day, mn_session, marker=marker, s=150, color=current_color)
            if interval == '60': interval = '  ' + interval
            custom_legend.add_entry(label=interval_str + 's', color=current_color, marker='o', linestyle='')
            #print(interval, predicted, mn_session, max_day)
            print(cat_name, interval, formatted1, formatted2)
            statistics_line = f'{cat_name}, interval: {interval}, {formatted1}, {formatted2}\n'
            tests_output.write(statistics_line)

    custom_legend.add_entry(label=f'Average, p > {alpha_level}', color='black', marker='+', linestyle='')
    custom_legend.add_entry(label=f'Average, p < {alpha_level}', color='black', marker='*', linestyle='')
    custom_legend.add_entry(label='Baseline Regression', color='gray', marker='None', linestyle='--')
    custom_legend.add_entry(label='Observation conf.', color='gray', marker='s', linestyle='None', alpha=0.1)

    Stats.plot_line(regression_result, colors['baseline'])
    if cat_name in ['Bernie', 'Citrine']: plt.ylim(0, 30)
    if cat_name in ['Elia', 'Minerva']: plt.ylim(0, 8)
    plt.xlim(-1, max_day_range)

    plt.title(cat_name, fontsize=18)

    ax = plt.gca()

    if plot_index in [0, 2]: plt.ylabel('Steps (1000)', fontsize=16)
    if plot_index not in [0,2]: ax.set_yticks([])
    if plot_index in [0, 1]: ax.set_xticks([])
    plt.xlabel('Days', fontsize=18)
    if plot_index in [0, 1]: plt.xlabel('')

    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_visible(False)
    ax.spines['bottom'].set_visible(False)

    plt.xticks(fontsize=16)  # X-axis tick labels font size
    plt.yticks(fontsize=16)  # Y-axis tick labels font size

    ax = plt.gca()
    ax.set_facecolor('#F1F0EA')


plt.subplot(2, 3, 3)
plt.axis('off')
custom_legend.draw_legend('upper left')
plt.tight_layout()
#
output_file = f"{output_folder}steps.png"
plt.savefig(output_file, dpi=300)
plt.show()
tests_output.close()

#     # plt.figure()
#     # plt.hist(residuals, color=colors['baseline'])
#     # plt.show()
#
#
# # output_file = f"{output_folder}phase_{phase}_averages.xlsx"
# # grps = data.groupby(['subject', 'interval'])
# # mn = grps.session.agg(['mean', 'std'])
# # mn.to_excel(output_file, index=True)